packages:
  - "apps/*"
  - "vendor/@emulators/*"
allowBuilds:
  agent-browser: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - aec-auth@0.3.1
overrides:
  "@types/react": 19.2.18
  "@types/react-dom": 19.2.4
