import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { catalogItems, readRegistry, wwwRoot } from './lib/registry-source.mts'

const siteDemosDir = path.join(wwwRoot, 'components/site/demos')
const registryExamplesDir = path.join(wwwRoot, 'registry/examples')
const outputPath = path.join(wwwRoot, 'components/site/demos.generated.tsx')

interface DemoSource {
  component: string
  module: string
  sourcePath: string
}

interface DemoSourceByItem {
  [item: string]: DemoSource
}

interface DemoAliasByItem {
  [item: string]: string
}

/** A template previews as the block it mounts; one module serves both names. */
const aliases: DemoAliasByItem = {
  'connections-page': 'connections-view',
}

const overrides: DemoSourceByItem = {
  'aps-viewer': {
    component: 'APSViewerDemo',
    module: './aps-viewer-demo',
    sourcePath: path.join(wwwRoot, 'components/site/aps-viewer-demo.tsx'),
  },
}

function pascalCase(name: string): string {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function lazyEntry(name: string, source: DemoSource): string {
  const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`
  return `  ${key}: lazy(async () => ({
    default: (await import('${source.module}')).${source.component},
  })) as DemoComponent,`
}

async function buildDemoRegistry(): Promise<{ contents: string; count: number }> {
  const registry = await readRegistry()
  const [siteFiles, registryFiles] = await Promise.all([
    readdir(siteDemosDir),
    readdir(registryExamplesDir),
  ])
  const siteFileSet = new Set(siteFiles)
  const registryFileSet = new Set(registryFiles)
  const sources: Array<[string, DemoSource]> = []

  for (const item of catalogItems(registry.items)) {
    const demoName = aliases[item.name] ?? item.name
    const fileName = `${demoName}-demo.tsx`
    const component = `${pascalCase(demoName)}Demo`
    let source = overrides[demoName]

    if (!source && siteFileSet.has(fileName)) {
      source = {
        component,
        module: `./demos/${demoName}-demo`,
        sourcePath: path.join(siteDemosDir, fileName),
      }
    }
    if (!source && registryFileSet.has(fileName)) {
      source = {
        component,
        module: `@/components/examples/${demoName}-demo`,
        sourcePath: path.join(registryExamplesDir, fileName),
      }
    }
    if (!source) continue

    const moduleContents = await readFile(source.sourcePath, 'utf8')
    if (!moduleContents.includes(`export function ${source.component}(`)) {
      throw new Error(
        `${path.relative(wwwRoot, source.sourcePath)} must export ${source.component}`,
      )
    }
    sources.push([item.name, source])
  }

  const entries = sources.map(([name, source]) => lazyEntry(name, source)).join('\n')
  const contents = `// Generated by scripts/build-demo-registry.mts. Edit the demo source, not this file.
import 'server-only'

import { type ComponentType, lazy } from 'react'

export type DemoComponent = ComponentType<{ urn?: string; titleAs?: 'h1' | 'h2' | 'h3' }>

const demos: Record<string, DemoComponent> = {
${entries}
}

export function getDemoComponent(name: string): DemoComponent | undefined {
  return demos[name]
}
`

  return { contents, count: sources.length }
}

async function main() {
  const check = process.argv.includes('--check')
  const { contents, count } = await buildDemoRegistry()
  const current = await readFile(outputPath, 'utf8').catch(() => null)

  if (current === contents) {
    console.log(`demo registry: ${count} entries up to date`)
    return
  }
  if (check) {
    console.error('demo registry: generated output is stale — run `pnpm registry:build`')
    process.exitCode = 1
    return
  }

  await writeFile(outputPath, contents, 'utf8')
  console.log(`demo registry: ${count} entries written`)
}

await main()
