/**
 * Generates the `registry:example` items — the pages "Open in v0" hands over.
 *
 * A bare component is a poor thing to drop into v0: it arrives with no page, no
 * data, and no imports it can resolve. So every demo source in
 * `registry/examples/` becomes an installable example item made of two files:
 * the demo component itself, and a generated `registry:page` wrapper that mounts
 * it at `app/examples/<item>/page.tsx`. v0 then opens something that renders.
 *
 * What is generated, and what is hand-written:
 * - hand-written — `registry/examples/<item>-demo.tsx`, the composition itself.
 *   These are real registry files (self-contained, installed specifiers, their
 *   own sample data), not site imports.
 * - generated — the page wrapper under `registry/examples/pages/`, and the
 *   example items in `registry.json`, whose dependencies are read straight out
 *   of the demo's imports so they cannot drift from what the file actually uses.
 *
 * Deterministic and idempotent: `--check` regenerates into memory and fails if
 * anything on disk differs, which is how `registry:verify` covers it.
 *
 * Run via `pnpm registry:build`, before `shadcn build`.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  AMBIENT_PACKAGES,
  aliasTargetFor,
  catalogItems,
  EXAMPLE_TYPE,
  formatRegistry,
  installedPath,
  isAliasSpecifier,
  namespace,
  PROJECT_PROVIDED_MODULES,
  packageNameFor,
  parseImports,
  type Registry,
  type RegistryItem,
  readRegistry,
  registryPath,
  withoutExtension,
  wwwRoot,
} from './lib/registry-source.mts'

const examplesDir = path.join(wwwRoot, 'registry/examples')
const pagesDir = path.join(examplesDir, 'pages')

/** How wide the generated page renders each demo. The only per-example knob. */
const PAGE_WIDTH: Record<string, string> = {
  'provider-sign-in-button': 'max-w-sm',
  'sign-in-card': 'max-w-md',
  'scope-picker': 'max-w-lg',
  'user-account-badge': 'max-w-sm',
  'token-status': 'max-w-lg',
  'connection-card': 'max-w-md',
  'status-tokens': 'max-w-3xl',
  'hub-switcher': 'max-w-sm',
  'project-picker': 'max-w-md',
  'version-set-select': 'max-w-sm',
  'model-status-card': 'max-w-md',
  'hub-browser': 'max-w-3xl',
  'file-picker-dialog': 'max-w-sm',
  'aps-viewer': 'max-w-6xl',
  'viewer-native-toolbar': 'max-w-6xl',
}

const DEFAULT_PAGE_WIDTH = 'max-w-md'

interface GeneratedFile {
  path: string
  contents: string
}

function pascalCase(name: string): string {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function pageWrapper(componentName: string, itemName: string, width: string): string {
  return `// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { ${componentName} } from '@/components/examples/${itemName}'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full ${width}">
        <${componentName} />
      </div>
    </main>
  )
}
`
}

/**
 * Resolves one import into the dependency that satisfies it: a cantera item, a
 * shadcn primitive, an npm package, or nothing at all when the consumer project
 * already provides it.
 */
function resolveDependency(
  specifier: string,
  providers: Map<string, string>,
): { registry?: string; npm?: string } {
  if (isAliasSpecifier(specifier)) {
    const target = aliasTargetFor(specifier)
    if (PROJECT_PROVIDED_MODULES.has(target)) return {}
    const owner = providers.get(target)
    if (owner) return { registry: `${namespace}/${owner}` }
    // Not ours: a shadcn primitive, referenced by its plain registry name.
    if (target.startsWith('components/ui/')) return { registry: path.posix.basename(target) }
    throw new Error(`Cannot resolve "${specifier}" to a registry dependency`)
  }
  if (specifier.startsWith('.')) {
    throw new Error(`Example demos must not use relative imports: "${specifier}"`)
  }
  const pkg = packageNameFor(specifier)
  return AMBIENT_PACKAGES.has(pkg) ? {} : { npm: pkg }
}

function sortDependencies(deps: string[]): string[] {
  const primitives = deps.filter((dep) => !dep.startsWith(namespace)).sort()
  const cantera = deps.filter((dep) => dep.startsWith(namespace)).sort()
  return [...primitives, ...cantera]
}

async function buildExamples(registry: Registry): Promise<{
  items: RegistryItem[]
  files: GeneratedFile[]
}> {
  const catalog = catalogItems(registry.items)
  const byName = new Map(catalog.map((item) => [item.name, item]))

  // Every installed module path in the catalog, mapped to the item that ships it.
  const providers = new Map<string, string>()
  for (const item of catalog) {
    for (const file of item.files ?? []) {
      providers.set(withoutExtension(installedPath(file)), item.name)
    }
  }

  // Catalog order, so registry.json reads as "every item, then its example".
  const catalogRank = new Map(catalog.map((item, index) => [item.name, index]))
  const sources = (await readdir(examplesDir, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith('-demo.tsx'))
    .map((entry) => entry.name)
    .sort(
      (a, b) =>
        (catalogRank.get(a.replace(/-demo\.tsx$/, '')) ?? Number.MAX_SAFE_INTEGER) -
        (catalogRank.get(b.replace(/-demo\.tsx$/, '')) ?? Number.MAX_SAFE_INTEGER),
    )

  const items: RegistryItem[] = []
  const files: GeneratedFile[] = []

  for (const source of sources) {
    const itemName = source.replace(/\.tsx$/, '')
    const baseName = itemName.replace(/-demo$/, '')
    const base = byName.get(baseName)
    if (!base) throw new Error(`${source} has no catalog item named "${baseName}"`)

    const contents = await readFile(path.join(examplesDir, source), 'utf8')
    const componentName = pascalCase(itemName)
    if (!contents.includes(`export function ${componentName}(`)) {
      throw new Error(`${source} must export a component named ${componentName}`)
    }

    const registryDependencies = new Set<string>([`${namespace}/${baseName}`])
    const dependencies = new Set<string>()
    for (const specifier of parseImports(contents).specifiers) {
      const resolved = resolveDependency(specifier, providers)
      if (resolved.registry) registryDependencies.add(resolved.registry)
      if (resolved.npm) dependencies.add(resolved.npm)
    }

    const pageFile = `${itemName}-page.tsx`
    files.push({
      path: path.join(pagesDir, pageFile),
      contents: pageWrapper(componentName, itemName, PAGE_WIDTH[baseName] ?? DEFAULT_PAGE_WIDTH),
    })

    items.push({
      name: itemName,
      type: EXAMPLE_TYPE,
      title: `${base.title} Example`,
      author: base.author,
      description: `A full page rendering ${base.title}, with its own sample data — what "Open in v0" hands over, and what to copy when wiring the component into a real screen.`,
      categories: base.categories,
      ...(dependencies.size > 0 ? { dependencies: [...dependencies].sort() } : {}),
      registryDependencies: sortDependencies([...registryDependencies]),
      files: [
        {
          path: `registry/examples/${source}`,
          type: 'registry:component',
          target: `components/examples/${itemName}.tsx`,
        },
        {
          path: `registry/examples/pages/${pageFile}`,
          type: 'registry:page',
          target: `app/examples/${baseName}/page.tsx`,
        },
      ],
    })
  }

  return { items, files }
}

async function main() {
  const check = process.argv.includes('--check')
  const registry = await readRegistry()
  const { items, files } = await buildExamples(registry)

  const next: Registry = { ...registry, items: [...catalogItems(registry.items), ...items] }
  files.push({ path: registryPath, contents: formatRegistry(next) })

  const stale: string[] = []
  for (const file of files) {
    const current = await readFile(file.path, 'utf8').catch(() => null)
    if (current === file.contents) continue
    stale.push(path.relative(wwwRoot, file.path))
    if (!check) await writeFile(file.path, file.contents, 'utf8')
  }

  if (check) {
    if (stale.length > 0) {
      console.error('examples: generated output is stale — run `pnpm registry:build`:')
      for (const file of stale) console.error(`  ${file}`)
      process.exitCode = 1
      return
    }
    console.log(`examples: ${items.length} items up to date`)
    return
  }

  console.log(`examples: ${items.length} items, ${stale.length} files written`)
}

await main()
