/**
 * Generates the server-only lookup that renders live demos in component docs.
 *
 * Demo modules stay split into one lazy import each, but the lookup itself runs
 * in the Server Component tree. Next can therefore resolve the selected demo
 * while prerendering or prefetching the route instead of discovering its module
 * from a client-only map after navigation.
 *
 * Sources are selected by convention, in catalog order:
 * - `components/site/demos/<item>-demo.tsx` for showcase-specific compositions.
 * - `registry/examples/<item>-demo.tsx` when the distributed example is also
 *   the showcase preview.
 * - An explicit override for previews that need a non-standard module or prop.
 *
 * Deterministic and idempotent: `--check` fails when the committed lookup is
 * stale, and `registry:verify` runs that check before verifying other output.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { catalogItems, readRegistry, wwwRoot } from './lib/registry-source.mts'

const siteDemosDir = path.join(wwwRoot, 'components/site/demos')
const registryExamplesDir = path.join(wwwRoot, 'registry/examples')
const outputPath = path.join(wwwRoot, 'components/site/demos.generated.tsx')

interface DemoSource {
  component: string
  module: string
  sourcePath: string
}

const overrides: Record<string, DemoSource> = {
  'aps-viewer': {
    component: 'APSViewerDemo',
    module: './aps-viewer-demo',
    sourcePath: path.join(wwwRoot, 'components/site/aps-viewer-demo.tsx'),
  },
}

function pascalCase(name: string): string {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function lazyEntry(name: string, source: DemoSource): string {
  const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`
  return `  ${key}: lazy(async () => ({
    default: (await import('${source.module}')).${source.component},
  })) as DemoComponent,`
}

async function buildDemoRegistry(): Promise<{ contents: string; count: number }> {
  const registry = await readRegistry()
  const [siteFiles, registryFiles] = await Promise.all([
    readdir(siteDemosDir),
    readdir(registryExamplesDir),
  ])
  const siteFileSet = new Set(siteFiles)
  const registryFileSet = new Set(registryFiles)
  const sources: Array<[string, DemoSource]> = []

  for (const item of catalogItems(registry.items)) {
    const fileName = `${item.name}-demo.tsx`
    const component = `${pascalCase(item.name)}Demo`
    let source = overrides[item.name]

    if (!source && siteFileSet.has(fileName)) {
      source = {
        component,
        module: `./demos/${item.name}-demo`,
        sourcePath: path.join(siteDemosDir, fileName),
      }
    }
    if (!source && registryFileSet.has(fileName)) {
      source = {
        component,
        module: `@/components/examples/${item.name}-demo`,
        sourcePath: path.join(registryExamplesDir, fileName),
      }
    }
    if (!source) continue

    const moduleContents = await readFile(source.sourcePath, 'utf8')
    if (!moduleContents.includes(`export function ${source.component}(`)) {
      throw new Error(
        `${path.relative(wwwRoot, source.sourcePath)} must export ${source.component}`,
      )
    }
    sources.push([item.name, source])
  }

  const entries = sources.map(([name, source]) => lazyEntry(name, source)).join('\n')
  const contents = `// Generated by scripts/build-demo-registry.mts. Edit the demo source, not this file.
import 'server-only'

import { type ComponentType, lazy } from 'react'

export type DemoComponent = ComponentType<{ urn?: string }>

const demos: Record<string, DemoComponent> = {
${entries}
}

export function getDemoComponent(name: string): DemoComponent | undefined {
  return demos[name]
}
`

  return { contents, count: sources.length }
}

async function main() {
  const check = process.argv.includes('--check')
  const { contents, count } = await buildDemoRegistry()
  const current = await readFile(outputPath, 'utf8').catch(() => null)

  if (current === contents) {
    console.log(`demo registry: ${count} entries up to date`)
    return
  }
  if (check) {
    console.error('demo registry: generated output is stale — run `pnpm registry:build`')
    process.exitCode = 1
    return
  }

  await writeFile(outputPath, contents, 'utf8')
  console.log(`demo registry: ${count} entries written`)
}

await main()
