import { defineMeta } from 'blume'

/**
 * Generated by `apps/www/scripts/build-docs.mts` — edit the registry, not this file.
 *
 * Ordered as `registry.json` orders its items: types first, then the tokens
 * and components built on them, then the wired blocks that compose those.
 */
export default defineMeta({
  title: 'Components',
  icon: 'blocks',
  pages: [
    'oauth-types',
    'aps-oauth-preset',
    'status-tokens',
    'provider-sign-in-button',
    'sign-in-card',
    'scope-picker',
    'user-account-badge',
    'token-status',
    'connection-card',
    'acc-sign-in',
    'connections-page',
  ],
})
