// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { ApsViewerDemo } from '@/components/examples/aps-viewer-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-6xl">
        <ApsViewerDemo />
      </div>
    </main>
  )
}
