// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { ConnectionCardDemo } from '@/components/examples/connection-card-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-md">
        <ConnectionCardDemo />
      </div>
    </main>
  )
}
