// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { FileDropZoneDemo } from '@/components/examples/file-drop-zone-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-lg">
        <FileDropZoneDemo />
      </div>
    </main>
  )
}
