// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { ModelStatusCardDemo } from '@/components/examples/model-status-card-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-md">
        <ModelStatusCardDemo />
      </div>
    </main>
  )
}
