// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { ScopePickerDemo } from '@/components/examples/scope-picker-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-lg">
        <ScopePickerDemo />
      </div>
    </main>
  )
}
