// Generated by scripts/build-examples.mts. Edit the demo, not this file.
import { VersionSetSelectDemo } from '@/components/examples/version-set-select-demo'

export default function Page() {
  return (
    <main className="flex min-h-svh items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <VersionSetSelectDemo />
      </div>
    </main>
  )
}
