// Generated by scripts/build-demo-registry.mts. Edit the demo source, not this file.
import 'server-only'

import { type ComponentType, lazy } from 'react'

export type DemoComponent = ComponentType<{ urn?: string; titleAs?: 'h1' | 'h2' | 'h3' }>

const demos: Record<string, DemoComponent> = {
  'status-tokens': lazy(async () => ({
    default: (await import('./demos/status-tokens-demo')).StatusTokensDemo,
  })) as DemoComponent,
  'provider-sign-in-button': lazy(async () => ({
    default: (await import('./demos/provider-sign-in-button-demo')).ProviderSignInButtonDemo,
  })) as DemoComponent,
  'sign-in-card': lazy(async () => ({
    default: (await import('./demos/sign-in-card-demo')).SignInCardDemo,
  })) as DemoComponent,
  'scope-picker': lazy(async () => ({
    default: (await import('./demos/scope-picker-demo')).ScopePickerDemo,
  })) as DemoComponent,
  'user-account-badge': lazy(async () => ({
    default: (await import('./demos/user-account-badge-demo')).UserAccountBadgeDemo,
  })) as DemoComponent,
  'token-status': lazy(async () => ({
    default: (await import('./demos/token-status-demo')).TokenStatusDemo,
  })) as DemoComponent,
  'connection-card': lazy(async () => ({
    default: (await import('./demos/connection-card-demo')).ConnectionCardDemo,
  })) as DemoComponent,
  'acc-connection-panel': lazy(async () => ({
    default: (await import('./demos/acc-connection-panel-demo')).AccConnectionPanelDemo,
  })) as DemoComponent,
  'acc-sign-in': lazy(async () => ({
    default: (await import('./demos/acc-sign-in-demo')).AccSignInDemo,
  })) as DemoComponent,
  'connections-view': lazy(async () => ({
    default: (await import('./demos/connections-view-demo')).ConnectionsViewDemo,
  })) as DemoComponent,
  'connections-page': lazy(async () => ({
    default: (await import('./demos/connections-view-demo')).ConnectionsViewDemo,
  })) as DemoComponent,
  'hub-switcher': lazy(async () => ({
    default: (await import('./demos/hub-switcher-demo')).HubSwitcherDemo,
  })) as DemoComponent,
  'project-picker': lazy(async () => ({
    default: (await import('./demos/project-picker-demo')).ProjectPickerDemo,
  })) as DemoComponent,
  'version-set-select': lazy(async () => ({
    default: (await import('./demos/version-set-select-demo')).VersionSetSelectDemo,
  })) as DemoComponent,
  'hub-browser': lazy(async () => ({
    default: (await import('@/components/examples/hub-browser-demo')).HubBrowserDemo,
  })) as DemoComponent,
  'hub-tree': lazy(async () => ({
    default: (await import('./demos/hub-tree-demo')).HubTreeDemo,
  })) as DemoComponent,
  finder: lazy(async () => ({
    default: (await import('./demos/finder-demo')).FinderDemo,
  })) as DemoComponent,
  'hub-sidebar': lazy(async () => ({
    default: (await import('./demos/hub-sidebar-demo')).HubSidebarDemo,
  })) as DemoComponent,
  'crew-avatar': lazy(async () => ({
    default: (await import('./demos/crew-avatar-demo')).CrewAvatarDemo,
  })) as DemoComponent,
  'file-picker-dialog': lazy(async () => ({
    default: (await import('@/components/examples/file-picker-dialog-demo')).FilePickerDialogDemo,
  })) as DemoComponent,
  'aps-viewer': lazy(async () => ({
    default: (await import('./aps-viewer-demo')).APSViewerDemo,
  })) as DemoComponent,
  'model-status-card': lazy(async () => ({
    default: (await import('./demos/model-status-card-demo')).ModelStatusCardDemo,
  })) as DemoComponent,
  'model-viewer-page': lazy(async () => ({
    default: (await import('./demos/model-viewer-page-demo')).ModelViewerPageDemo,
  })) as DemoComponent,
  'model-upload-page': lazy(async () => ({
    default: (await import('./demos/model-upload-page-demo')).ModelUploadPageDemo,
  })) as DemoComponent,
  'file-drop-zone': lazy(async () => ({
    default: (await import('@/components/examples/file-drop-zone-demo')).FileDropZoneDemo,
  })) as DemoComponent,
  'copy-field': lazy(async () => ({
    default: (await import('@/components/examples/copy-field-demo')).CopyFieldDemo,
  })) as DemoComponent,
  'provisioning-notice': lazy(async () => ({
    default: (await import('@/components/examples/provisioning-notice-demo')).ProvisioningNoticeDemo,
  })) as DemoComponent,
}

export function getDemoComponent(name: string): DemoComponent | undefined {
  return demos[name]
}
